#ifndef CLOTH_CONSTANTS_INCLUDED
#define CLOTH_CONSTANTS_INCLUDED

#define MAX_PARTICLES_PER_CLOTH         2048
#define PARTICLES_PER_THREAD            2
#define MAX_CONSTRAINT_BATCHES          12
#define MAX_TRIS_PER_PARTICLE           6
#define FILLED_FAN_BIT	                0x8000

#endif // CLOTH_CONSTANTS_INCLUDED
