#ifndef CLOTH_CONSTANTS_INCLUDED
#define CLOTH_CONSTANTS_INCLUDED

#define MAX_PARTICLES_PER_CLOTH     2048
#define MAX_CONSTRAINT_BATCHES      8
#define PARTICLES_PER_THREAD        2

#endif // CLOTH_CONSTANTS_INCLUDED
