#ifndef CLOTH_CONSTANTS_INCLUDED
#define CLOTH_CONSTANTS_INCLUDED

#define MAX_PARTICLES_PER_CLOTH         2048
#define PARTICLES_PER_THREAD            2
#define MAX_CONSTRAINT_BATCHES          12
#define MAX_FAN_BLADES_PER_PARTICLE     8
#define INVALID_FAN_INDEX	            0xFFFF

#endif // CLOTH_CONSTANTS_INCLUDED
